"""Frengression versus Frugal Flows on the paper's existing binary ATE DGP.

The observational data are generated by the unchanged data.causl function
from xwshen51/frengression/data_causl/data_causl.R. The causal outcome margins
are N(0, 1) and N(2, 1), so the ATE and all reference distribution metrics
are calculated from their specified laws, not reference Monte Carlo samples.

The two fits receive the same R-generated observational data for each seed.
Simulation from a fitted generative model still uses finitely many draws;
increase --mc to make this numerical evaluation error small.
"""

from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
PACKAGE_SRC = HERE.parent / "src"
if (PACKAGE_SRC / "frengression" / "__init__.py").is_file():
    sys.path.insert(0, str(PACKAGE_SRC))


def generate_causl(n: int, seed: int, strength_instr: float = 0.0):
    """Run the same causl binary generator and parameter values as binary.ipynb."""
    executable = shutil.which("Rscript")
    if executable is None:
        raise RuntimeError("Rscript is required. Install R and the R package 'causl'.")
    with tempfile.TemporaryDirectory(prefix="frengression_causl_") as tmp:
        output = Path(tmp) / "observations.csv"
        proc = subprocess.run(
            [executable, str(HERE / "causl_binary.R"), str(output),
             str(n), str(seed), str(strength_instr)],
            text=True, capture_output=True, check=False,
        )
        if proc.returncode:
            raise RuntimeError(
                f"causl generation failed (Rscript exit {proc.returncode}).\n"
                f"{proc.stderr[-3000:]}\n{proc.stdout[-1000:]}"
            )
        frame = pd.read_csv(output)
    expected = [f"X{i}" for i in range(1, 11)] + ["A", "y"]
    if list(frame.columns) != expected or len(frame) != n:
        raise RuntimeError(f"Unexpected causl output shape or columns: {frame.shape}, {list(frame.columns)}")
    x = frame[["A"]].to_numpy(dtype=np.float32)
    z = frame[expected[:10]].to_numpy(dtype=np.float32)
    y = frame[["y"]].to_numpy(dtype=np.float32)
    if not np.isfinite(np.concatenate((x, z, y), axis=1)).all() or not np.isin(x, (0, 1)).all():
        raise RuntimeError("The causl output contains invalid values or non-binary treatment")
    return x, z, y


def _normal_w1_exact(draw, mean: float, sd: float = 1.0) -> float:
    """Exact W1 of an empirical 1D distribution versus a Gaussian law.

    Integrate |empirical quantile - Normal quantile| analytically on every
    empirical quantile interval, splitting each interval at their crossing.
    """
    x = np.sort(np.asarray(draw, dtype=float).reshape(-1))
    m = len(x)
    a, b = np.arange(m) / m, (np.arange(m) + 1) / m
    crossing = np.clip(norm.cdf((x - mean) / sd), a, b)

    def antiderivative(u):
        # Integral of x - (mean + sd * Phi^{-1}(u)); pdf at 0 and 1 is 0.
        density = norm.pdf(norm.ppf(u))
        return (x - mean) * u + sd * density

    return float(np.sum(2 * antiderivative(crossing)
                        - antiderivative(a) - antiderivative(b)))


def _normal_energy_exact(draw, mean: float, sd: float = 1.0) -> float:
    """SciPy energy-distance convention, with Gaussian expectations in closed form."""
    x = np.sort(np.asarray(draw, dtype=float).reshape(-1))
    m = len(x)
    t = (x - mean) / sd
    cross = sd * np.mean(2 * norm.pdf(t) + t * (2 * norm.cdf(t) - 1))
    within = 2 * np.dot(2 * np.arange(1, m + 1) - m - 1, x) / m**2
    normal_within = 2 * sd / np.sqrt(np.pi)
    return float(np.sqrt(max(0.0, 2 * cross - within - normal_within)))


def score(draw0, draw1, ate: float = 2.0):
    """The exact causal-margin truths are N(0,1) and N(ate,1)."""
    d0, d1 = (np.asarray(v, dtype=float).reshape(-1) for v in (draw0, draw1))
    if min(len(d0), len(d1)) < 2 or not np.isfinite(d0).all() or not np.isfinite(d1).all():
        raise ValueError("Need at least two finite fitted draws per treatment arm")
    q = np.array([0.1, 0.5, 0.9])
    estimated_ate = float(d1.mean() - d0.mean())
    return dict(
        true_ate=ate, estimated_ate=estimated_ate,
        ate_error=abs(estimated_ate - ate),
        true_mean0=0.0, estimated_mean0=float(d0.mean()),
        true_mean1=ate, estimated_mean1=float(d1.mean()),
        wasserstein_mean=(_normal_w1_exact(d0, 0) + _normal_w1_exact(d1, ate)) / 2,
        energy_mean=(_normal_energy_exact(d0, 0) + _normal_energy_exact(d1, ate)) / 2,
        quantile_mae=float(np.mean([np.mean(np.abs(np.quantile(d, q) - norm.ppf(q, loc=mu)))
                                    for d, mu in ((d0, 0), (d1, ate))])),
        model_draw_ate_se=float(np.sqrt(d0.var(ddof=1) / len(d0) + d1.var(ddof=1) / len(d1))),
    )


def fit_frengression(x, z, y, seed: int, iterations: int, mc: int):
    import torch
    from frengression import Frengression

    torch.manual_seed(seed)
    torch.set_num_threads(1)
    xt, zt, yt = (torch.as_tensor(v, dtype=torch.float32) for v in (x, z, y))
    model = Frengression(x_dim=1, y_dim=1, z_dim=z.shape[1],
                         num_layer=3, hidden_dim=100, noise_dim=1,
                         x_binary=True, z_binary_dims=0, device=torch.device("cpu"))
    start = time.perf_counter()
    model.train_y(xt, zt, yt, num_iters=iterations, lr=1e-4,
                  print_every_iter=max(1, iterations // 5), tol=0)
    seconds = time.perf_counter() - start
    draws = []
    for arm in (0, 1):
        sample = model.sample_causal_margin(
            torch.tensor([arm], dtype=torch.int32), sample_size=mc)
        draws.append(np.asarray(sample.detach().cpu()).reshape(-1))
    return draws, seconds


def run(args):
    # This implementation is shared with the earlier exploratory comparison.
    from compare_frugal_flows import fit_frugal_flows

    rows = []
    for rep in range(args.repeats):
        seed = args.seed + rep
        x, z, y = generate_causl(args.n, seed, args.strength_instr)
        for method in args.methods:
            print(f"Fitting {method}: n={args.n}, p=10, seed={seed}, "
                  f"instrument strength={args.strength_instr}", flush=True)
            if method == "frengression":
                draws, seconds = fit_frengression(x, z, y, seed, args.fr_iters, args.mc)
            else:
                draws, seconds = fit_frugal_flows(
                    x, z, y, seed, args.flow_epochs, args.marginal_epochs, args.mc)
            row = dict(seed=seed, n=args.n, strength_instr=args.strength_instr,
                       method=method, seconds=seconds,
                       fr_iters=args.fr_iters if method == "frengression" else "",
                       flow_epochs=args.flow_epochs if method == "frugal_flows" else "",
                       **score(draws[0], draws[1]))
            print(row, flush=True)
            rows.append(row)
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    print(f"Wrote {len(rows)} rows to {out}")
    return rows


def cli():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, default=5000)
    parser.add_argument("--repeats", type=int, default=1)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--strength-instr", type=float, default=0.0)
    parser.add_argument("--fr-iters", type=int, default=1000)
    parser.add_argument("--flow-epochs", type=int, default=2000)
    parser.add_argument("--marginal-epochs", type=int, default=400)
    parser.add_argument("--mc", type=int, default=10000)
    parser.add_argument("--methods", nargs="+", choices=("frengression", "frugal_flows"),
                        default=["frengression", "frugal_flows"])
    parser.add_argument("--output", default="causl_ff_comparison.csv")
    args = parser.parse_args()
    if min(args.n, args.repeats, args.fr_iters, args.flow_epochs,
           args.marginal_epochs, args.mc) < 2:
        parser.error("n, repeats, training budgets, and mc must be at least 2")
    run(args)


if __name__ == "__main__":
    cli()
