"""Frengression versus Frugal Flows on the paper's existing binary ATE DGP.

The observational data are generated by the unchanged data.causl function
from xwshen51/frengression/data_causl/data_causl.R. The causal outcome margins
are N(0, 1) and N(2, 1), so the ATE and all reference distribution metrics
are calculated from their specified laws, not reference Monte Carlo samples.

The two fits receive the same R-generated observational data for each seed.
The default is 400 fitted outcome draws per arm, matching binary.ipynb.
Sampling counts are recorded and checked before cached results are reused.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path
from datetime import datetime, timezone
from importlib import metadata

import numpy as np
import pandas as pd
from scipy.stats import norm

HERE = Path(__file__).resolve().parent
PACKAGE_SRC = HERE.parent / "src"
if (PACKAGE_SRC / "frengression" / "__init__.py").is_file():
    sys.path.insert(0, str(PACKAGE_SRC))


def generate_causl(n: int, seed: int, strength_instr: float = 0.0):
    """Run the same causl binary generator and parameter values as binary.ipynb."""
    executable = shutil.which("Rscript")
    if executable is None:
        raise RuntimeError("Rscript is required. Install R and the R package 'causl'.")
    with tempfile.TemporaryDirectory(prefix="frengression_causl_") as tmp:
        output = Path(tmp) / "observations.csv"
        proc = subprocess.run(
            [executable, str(HERE / "causl_binary.R"), str(output),
             str(n), str(seed), str(strength_instr)],
            text=True, capture_output=True, check=False,
        )
        if proc.returncode:
            raise RuntimeError(
                f"causl generation failed (Rscript exit {proc.returncode}).\n"
                f"{proc.stderr[-3000:]}\n{proc.stdout[-1000:]}"
            )
        frame = pd.read_csv(output)
    expected = [f"X{i}" for i in range(1, 11)] + ["A", "y"]
    if list(frame.columns) != expected or len(frame) != n:
        raise RuntimeError(f"Unexpected causl output shape or columns: {frame.shape}, {list(frame.columns)}")
    x = frame[["A"]].to_numpy(dtype=np.float32)
    z = frame[expected[:10]].to_numpy(dtype=np.float32)
    y = frame[["y"]].to_numpy(dtype=np.float32)
    if not np.isfinite(np.concatenate((x, z, y), axis=1)).all() or not np.isin(x, (0, 1)).all():
        raise RuntimeError("The causl output contains invalid values or non-binary treatment")
    return x, z, y


def _normal_w1_exact(draw, mean: float, sd: float = 1.0) -> float:
    """Exact W1 of an empirical 1D distribution versus a Gaussian law.

    Integrate |empirical quantile - Normal quantile| analytically on every
    empirical quantile interval, splitting each interval at their crossing.
    """
    x = np.sort(np.asarray(draw, dtype=float).reshape(-1))
    m = len(x)
    a, b = np.arange(m) / m, (np.arange(m) + 1) / m
    crossing = np.clip(norm.cdf((x - mean) / sd), a, b)

    def antiderivative(u):
        # Integral of x - (mean + sd * Phi^{-1}(u)); pdf at 0 and 1 is 0.
        density = norm.pdf(norm.ppf(u))
        return (x - mean) * u + sd * density

    return float(np.sum(2 * antiderivative(crossing)
                        - antiderivative(a) - antiderivative(b)))


def _normal_energy_exact(draw, mean: float, sd: float = 1.0) -> float:
    """SciPy energy-distance convention, with Gaussian expectations in closed form."""
    x = np.sort(np.asarray(draw, dtype=float).reshape(-1))
    m = len(x)
    t = (x - mean) / sd
    cross = sd * np.mean(2 * norm.pdf(t) + t * (2 * norm.cdf(t) - 1))
    within = 2 * np.dot(2 * np.arange(1, m + 1) - m - 1, x) / m**2
    normal_within = 2 * sd / np.sqrt(np.pi)
    return float(np.sqrt(max(0.0, 2 * cross - within - normal_within)))


def score(draw0, draw1, ate: float = 2.0):
    """The exact causal-margin truths are N(0,1) and N(ate,1)."""
    d0, d1 = (np.asarray(v, dtype=float).reshape(-1) for v in (draw0, draw1))
    if min(len(d0), len(d1)) < 2 or not np.isfinite(d0).all() or not np.isfinite(d1).all():
        raise ValueError("Need at least two finite fitted draws per treatment arm")
    q = np.array([0.1, 0.5, 0.9])
    estimated_ate = float(d1.mean() - d0.mean())
    return dict(
        true_ate=ate, estimated_ate=estimated_ate,
        ate_error=abs(estimated_ate - ate),
        true_mean0=0.0, estimated_mean0=float(d0.mean()),
        true_mean1=ate, estimated_mean1=float(d1.mean()),
        wasserstein_mean=(_normal_w1_exact(d0, 0) + _normal_w1_exact(d1, ate)) / 2,
        energy_mean=(_normal_energy_exact(d0, 0) + _normal_energy_exact(d1, ate)) / 2,
        quantile_mae=float(np.mean([np.mean(np.abs(np.quantile(d, q) - norm.ppf(q, loc=mu)))
                                    for d, mu in ((d0, 0), (d1, ate))])),
        model_draw_ate_se=float(np.sqrt(d0.var(ddof=1) / len(d0) + d1.var(ddof=1) / len(d1))),
    )


def fit_frengression(x, z, y, seed: int, iterations: int, mc: int):
    import torch
    from frengression import Frengression

    torch.manual_seed(seed)
    torch.set_num_threads(1)
    xt, zt, yt = (torch.as_tensor(v, dtype=torch.float32) for v in (x, z, y))
    model = Frengression(x_dim=1, y_dim=1, z_dim=z.shape[1],
                         num_layer=3, hidden_dim=100, noise_dim=1,
                         x_binary=True, z_binary_dims=0, device=torch.device("cpu"))
    start = time.perf_counter()
    model.train_y(xt, zt, yt, num_iters=iterations, lr=1e-4,
                  print_every_iter=max(1, iterations // 5), tol=0)
    seconds = time.perf_counter() - start
    draws = []
    for arm in (0, 1):
        sample = model.sample_causal_margin(
            torch.tensor([arm], dtype=torch.int32), sample_size=mc)
        draws.append(np.asarray(sample.detach().cpu()).reshape(-1))
    return draws, seconds


def fit_frugal_flows_official(x, z, y, seed: int, epochs: int,
                              marginal_epochs: int, mc: int):
    """Use the authors' benchmarking hyperparameters for a 10-D copula.

    The dictionaries are imported from the pinned Frugal Flows repository
    itself; only the epoch limit and progress display are
    overridden for this experiment. Their 10-D setting uses a wider copula
    conditioner than our earlier exploratory comparison.
    """
    import inspect
    import jax
    import jax.numpy as jnp
    from flowjax.train import fit_to_data
    from frugal_flows.benchmarking import (
        FrugalFlowModel, hyperparam_dict, causal_margin_hyperparam_dict,
    )

    if "data" not in inspect.signature(fit_to_data).parameters:
        raise RuntimeError("Frugal Flows requires flowjax==19.1.0 in this kernel; restart after installing.")
    jax.config.update("jax_enable_x64", True)
    model = FrugalFlowModel(
        Y=jnp.asarray(y, dtype=jnp.float64),
        X=jnp.asarray(x, dtype=jnp.float64),
        Z_cont=jnp.asarray(z, dtype=jnp.float64),
    )
    flow_kwargs = dict(hyperparam_dict)
    flow_kwargs.update(max_epochs=epochs, max_patience=min(100, epochs),
                       show_progress=False)
    causal_kwargs = dict(causal_margin_hyperparam_dict)
    start = time.perf_counter()
    model.train_marginal_cdfs(
        jax.random.key(seed),
        dict(max_epochs=marginal_epochs,
             max_patience=min(100, marginal_epochs)),
    )
    model.train_frugal_flow(
        jax.random.key(seed + 10000), flow_kwargs,
        "flexible_continuous", causal_kwargs,
    )
    _ = float(np.asarray(model.min_val_loss))
    seconds = time.perf_counter() - start
    draws = [
        np.asarray(model.sample_do(
            jax.random.key(seed + 20000 + arm), arm, mc)).reshape(-1)
        for arm in (0, 1)
    ]
    return draws, seconds


RESULT_COLUMNS = [
    'seed', 'n', 'strength_instr', 'method', 'seconds', 'fr_iters', 'flow_epochs',
    'marginal_epochs', 'mc_draws_per_arm', 'draws0', 'draws1', 'ff_config',
    'true_ate', 'estimated_ate', 'ate_error', 'true_mean0', 'estimated_mean0',
    'true_mean1', 'estimated_mean1', 'wasserstein_mean', 'energy_mean',
    'quantile_mae', 'model_draw_ate_se',
]


def checked_results(rows, args):
    """Reject unknown draw counts, mismatched budgets and duplicate cache rows."""
    if not set(RESULT_COLUMNS).issubset(rows.columns):
        raise ValueError('Cached results lack the current sampling/settings metadata; do not reuse them')
    if rows.empty:
        return rows
    if rows.duplicated(['seed', 'method']).any():
        raise ValueError('Duplicate method/seed cache rows')
    seeds = set(range(args.seed, args.seed + args.repeats))
    valid = (set(rows.method).issubset(set(args.methods))
             and set(rows.seed).issubset(seeds)
             and (rows.n == args.n).all()
             and np.allclose(rows.strength_instr, args.strength_instr)
             and (rows.mc_draws_per_arm == args.mc).all()
             and (rows.draws0 == args.mc).all() and (rows.draws1 == args.mc).all()
             and (rows.true_ate == 2.0).all())
    numeric = rows[['estimated_ate', 'ate_error', 'model_draw_ate_se', 'seconds',
                    'wasserstein_mean', 'energy_mean', 'quantile_mae']].to_numpy(dtype=float)
    valid = valid and np.isfinite(numeric).all()
    for method, group in rows.groupby('method'):
        if method == 'frengression':
            valid = valid and (group.fr_iters == args.fr_iters).all()
        else:
            config = 'benchmarking_default_10d' if method == 'frugal_flows_official' else 'compact_exploratory'
            valid = (valid and (group.flow_epochs == args.flow_epochs).all()
                     and (group.marginal_epochs == args.marginal_epochs).all()
                     and (group.ff_config == config).all())
    if not valid:
        raise ValueError('Cached results do not match the requested data, training or outcome draw settings')
    return rows


def _write_csv(frame, path):
    temporary = path.with_suffix(path.suffix + '.tmp')
    frame.to_csv(temporary, index=False)
    temporary.replace(path)


def run(args):
    """Checkpoint each successful method; retry only missing fits on rerun."""
    from compare_frugal_flows import fit_frugal_flows

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    cached = (checked_results(pd.read_csv(out), args) if out.is_file()
              else pd.DataFrame(columns=RESULT_COLUMNS))
    rows = cached.to_dict('records')
    completed = {(int(row['seed']), row['method']) for row in rows}
    failure_path = out.with_name(out.stem + '_failures.csv')
    failure_columns = ['seed', 'method', 'stage', 'error', 'attempted_at_utc']
    failures = pd.read_csv(failure_path).to_dict('records') if failure_path.is_file() else []

    def fail(seed, method, stage, error):
        failures.append(dict(seed=seed, method=method, stage=stage,
                             error=f'{type(error).__name__}: {error}',
                             attempted_at_utc=datetime.now(timezone.utc).isoformat()))
        _write_csv(pd.DataFrame(failures, columns=failure_columns), failure_path)
        print(f'Failed {method}, seed={seed}: {error}', flush=True)

    versions = {}
    for name in ('torch', 'engression', 'jax', 'flowjax', 'frugal-flows', 'numpy', 'scipy'):
        try:
            versions[name] = metadata.version(name)
        except metadata.PackageNotFoundError:
            versions[name] = None
    commit = subprocess.run(['git', '-C', str(HERE.parent), 'rev-parse', 'HEAD'],
                            capture_output=True, text=True)
    info = dict(settings=vars(args), outcome_draws_per_arm=args.mc, true_ate=2.0,
                repository_commit=commit.stdout.strip() if commit.returncode == 0 else None,
                versions=versions,
                sampling_note='Each ATE is mean(draw1)-mean(draw0), using mc draws per arm',
                uncertainty_note='model_draw_ate_se is conditional on the fitted model')
    out.with_suffix('.metadata.json').write_text(json.dumps(info, indent=2), encoding='utf-8')
    for rep in range(args.repeats):
        seed = args.seed + rep
        missing = [method for method in args.methods if (seed, method) not in completed]
        if not missing:
            print(f'Reusing completed seed={seed}, mc={args.mc} per arm', flush=True)
            continue
        try:
            x, z, y = generate_causl(args.n, seed, args.strength_instr)
        except Exception as error:
            fail(seed, 'data_generation', 'data_generation', error)
            continue
        for method in missing:
            try:
                print(f'Fitting {method}: n={args.n}, seed={seed}, '
                      f'strength={args.strength_instr}, mc={args.mc} per arm', flush=True)
                if method == 'frengression':
                    draws, seconds = fit_frengression(x, z, y, seed, args.fr_iters, args.mc)
                elif method == 'frugal_flows_official':
                    draws, seconds = fit_frugal_flows_official(
                        x, z, y, seed, args.flow_epochs, args.marginal_epochs, args.mc)
                else:
                    draws, seconds = fit_frugal_flows(
                        x, z, y, seed, args.flow_epochs, args.marginal_epochs, args.mc)
                draws = [np.asarray(draw, dtype=float).reshape(-1) for draw in draws]
                if len(draws) != 2 or any(len(draw) != args.mc for draw in draws):
                    raise ValueError('Fitted sampler returned an unexpected number of outcomes')
                row = dict(seed=seed, n=args.n, strength_instr=args.strength_instr,
                           method=method, seconds=seconds,
                           fr_iters=args.fr_iters if method == 'frengression' else '',
                           flow_epochs=args.flow_epochs if method != 'frengression' else '',
                           marginal_epochs=args.marginal_epochs if method != 'frengression' else '',
                           mc_draws_per_arm=args.mc, draws0=len(draws[0]), draws1=len(draws[1]),
                           ff_config=('benchmarking_default_10d' if method == 'frugal_flows_official'
                                      else 'compact_exploratory' if method == 'frugal_flows' else ''),
                           **score(draws[0], draws[1]))
                checked_results(pd.DataFrame([row], columns=RESULT_COLUMNS), args)
                rows.append(row)
                completed.add((seed, method))
                _write_csv(pd.DataFrame(rows, columns=RESULT_COLUMNS), out)
                print(row, flush=True)
            except Exception as error:
                fail(seed, method, 'fit_or_score', error)
    _write_csv(pd.DataFrame(rows, columns=RESULT_COLUMNS), out)
    _write_csv(pd.DataFrame(failures, columns=failure_columns), failure_path)
    print(f'Saved {len(rows)} completed method rows to {out}', flush=True)
    return rows


def cli():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--n", type=int, default=5000)
    parser.add_argument("--repeats", type=int, default=1)
    parser.add_argument("--seed", type=int, default=2026)
    parser.add_argument("--strength-instr", type=float, default=0.0)
    parser.add_argument("--fr-iters", type=int, default=1000)
    parser.add_argument("--flow-epochs", type=int, default=1000)
    parser.add_argument("--marginal-epochs", type=int, default=400)
    parser.add_argument("--mc", type=int, default=400,
                        help="Fitted outcome draws per arm; 400 matches the paper's binary ATE experiment")
    parser.add_argument("--methods", nargs="+",
                        choices=("frengression", "frugal_flows",
                                 "frugal_flows_official"),
                        default=["frengression", "frugal_flows_official"])
    parser.add_argument("--output", default="causl_ff_comparison.csv")
    args = parser.parse_args()
    if min(args.n, args.repeats, args.fr_iters, args.flow_epochs,
           args.marginal_epochs, args.mc) < 2:
        parser.error("n, repeats, training budgets, and mc must be at least 2")
    run(args)


if __name__ == "__main__":
    cli()

